name: Deploy
on:
  push:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.0
    - name: Check
      run: cargo check
    - name: GitHub Action for flyctl
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only -a chrisbot
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

